/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiTarjetaRouteImport } from './routes/mi-tarjeta'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as TEnlaceRouteImport } from './routes/t.$enlace'
import { Route as ApiManifestEnlaceRouteImport } from './routes/api.manifest.$enlace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiTarjetaRoute = MiTarjetaRouteImport.update({
  id: '/mi-tarjeta',
  path: '/mi-tarjeta',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TEnlaceRoute = TEnlaceRouteImport.update({
  id: '/t/$enlace',
  path: '/t/$enlace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManifestEnlaceRoute = ApiManifestEnlaceRouteImport.update({
  id: '/api/manifest/$enlace',
  path: '/api/manifest/$enlace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mi-tarjeta': typeof MiTarjetaRoute
  '/registro': typeof RegistroRoute
  '/t/$enlace': typeof TEnlaceRoute
  '/api/manifest/$enlace': typeof ApiManifestEnlaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mi-tarjeta': typeof MiTarjetaRoute
  '/registro': typeof RegistroRoute
  '/t/$enlace': typeof TEnlaceRoute
  '/api/manifest/$enlace': typeof ApiManifestEnlaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mi-tarjeta': typeof MiTarjetaRoute
  '/registro': typeof RegistroRoute
  '/t/$enlace': typeof TEnlaceRoute
  '/api/manifest/$enlace': typeof ApiManifestEnlaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/mi-tarjeta' | '/registro' | '/t/$enlace' | '/api/manifest/$enlace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mi-tarjeta' | '/registro' | '/t/$enlace' | '/api/manifest/$enlace'
  id:
    | '__root__'
    | '/'
    | '/mi-tarjeta'
    | '/registro'
    | '/t/$enlace'
    | '/api/manifest/$enlace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiTarjetaRoute: typeof MiTarjetaRoute
  RegistroRoute: typeof RegistroRoute
  TEnlaceRoute: typeof TEnlaceRoute
  ApiManifestEnlaceRoute: typeof ApiManifestEnlaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-tarjeta': {
      id: '/mi-tarjeta'
      path: '/mi-tarjeta'
      fullPath: '/mi-tarjeta'
      preLoaderRoute: typeof MiTarjetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$enlace': {
      id: '/t/$enlace'
      path: '/t/$enlace'
      fullPath: '/t/$enlace'
      preLoaderRoute: typeof TEnlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manifest/$enlace': {
      id: '/api/manifest/$enlace'
      path: '/api/manifest/$enlace'
      fullPath: '/api/manifest/$enlace'
      preLoaderRoute: typeof ApiManifestEnlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiTarjetaRoute: MiTarjetaRoute,
  RegistroRoute: RegistroRoute,
  TEnlaceRoute: TEnlaceRoute,
  ApiManifestEnlaceRoute: ApiManifestEnlaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
